# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dust_sireinfect_alloc <- function(r_data, step, n_particles, n_threads, seed) {
    .Call(`_sireinfect_dust_sireinfect_alloc`, r_data, step, n_particles, n_threads, seed)
}

dust_sireinfect_run <- function(ptr, step_end) {
    .Call(`_sireinfect_dust_sireinfect_run`, ptr, step_end)
}

dust_sireinfect_reset <- function(ptr, r_data, step) {
    .Call(`_sireinfect_dust_sireinfect_reset`, ptr, r_data, step)
}

dust_sireinfect_state <- function(ptr, r_index) {
    .Call(`_sireinfect_dust_sireinfect_state`, ptr, r_index)
}

dust_sireinfect_step <- function(ptr) {
    .Call(`_sireinfect_dust_sireinfect_step`, ptr)
}

dust_sireinfect_reorder <- function(ptr, r_index) {
    invisible(.Call(`_sireinfect_dust_sireinfect_reorder`, ptr, r_index))
}

