# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dust_sireinfect_alloc <- function(r_data, step, n_particles, n_threads, n_generators, seed) {
    .Call('_sireinfectcaa6dd97_dust_sireinfect_alloc', PACKAGE = 'sireinfectcaa6dd97', r_data, step, n_particles, n_threads, n_generators, seed)
}

dust_sireinfect_run <- function(ptr, step_end) {
    .Call('_sireinfectcaa6dd97_dust_sireinfect_run', PACKAGE = 'sireinfectcaa6dd97', ptr, step_end)
}

dust_sireinfect_reset <- function(ptr, r_data, step) {
    .Call('_sireinfectcaa6dd97_dust_sireinfect_reset', PACKAGE = 'sireinfectcaa6dd97', ptr, r_data, step)
}

dust_sireinfect_state <- function(ptr, r_index) {
    .Call('_sireinfectcaa6dd97_dust_sireinfect_state', PACKAGE = 'sireinfectcaa6dd97', ptr, r_index)
}

dust_sireinfect_step <- function(ptr) {
    .Call('_sireinfectcaa6dd97_dust_sireinfect_step', PACKAGE = 'sireinfectcaa6dd97', ptr)
}

dust_sireinfect_reorder <- function(ptr, r_index) {
    invisible(.Call('_sireinfectcaa6dd97_dust_sireinfect_reorder', PACKAGE = 'sireinfectcaa6dd97', ptr, r_index))
}

