## Generated by dust (version 0.0.7) - do not edit
sireinfect <- R6::R6Class(
"dust",
cloneable = FALSE,

private = list(
  data = NULL,
  ptr = NULL
),

public = list(
  name = "sireinfect",

  initialize = function(data, step, n_particles, n_threads = 1L,
                        n_generators = 1L, seed = 1L) {
    res <- dust_sireinfect_alloc(data, step, n_particles,
                      n_threads, n_generators, seed)
    private$ptr <- res[[1L]]
    private$data <- res[[2L]]
  },

  run = function(step_end) {
    dust_sireinfect_run(private$ptr, step_end)
  },

  reset = function(data, step) {
    private$data <- dust_sireinfect_reset(private$ptr, data, step)
    invisible()
  },

  state = function(index = NULL) {
    dust_sireinfect_state(private$ptr, index)
  },

  step = function() {
    dust_sireinfect_step(private$ptr)
  },

  reorder = function(index) {
    dust_sireinfect_reorder(private$ptr, as.integer(index))
    invisible()
  },

  info = function() {
    private$data
  }
))
## Generated by odin.dust (version 0.0.3) - do not edit
sireinfect$set("public", "index", function () 
{
    n <- vapply(self$info(), prod, numeric(1))
    Map(seq.int, to = cumsum(n), by = 1L, length.out = n)
})
